spring:
  application:
    name: beans-journal
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: beans-journal-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    mongodb:
      uri: mongodb://${DB_HOST}/${DB_NAME}?authSource=admin&replicaSet=${DB_REPLICASET}
      database: beansjournal
  logging:
    level:
      org.springframework.data.mongodb.core: DEBUG

server:
  port:
    8006

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles:
        all:
          - 0.5
          - 0.95
          - 0.99
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: "beans-journal"
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    prometheus:
      access: unrestricted